//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VtcIts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Building
    {
        public Building()
        {
            this.Rooms = new HashSet<Room>();
            this.People = new HashSet<Person>();
        }
    
        public int Id { get; set; }
        public int LocationId { get; set; }
        public string Name { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual ICollection<Person> People { get; set; }
    }
}
