//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VtcIts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public Meeting()
        {
            this.MeetingParticipants = new HashSet<MeetingParticipant>();
            this.ExternalLocations = new HashSet<ExternalLocation>();
            this.Rooms = new HashSet<Room>();
        }
    
        public int Id { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public string Title { get; set; }
        public VtcIts.MeetingRequestSource Source { get; set; }
        public string FootprintsTicket { get; set; }
        public int TechnicianId { get; set; }
        public int RequesterId { get; set; }
        public Nullable<int> SeriesId { get; set; }
        public VtcIts.MeetingStatus Status { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Started { get; set; }
        public Nullable<System.DateTime> Closed { get; set; }
        public bool SurveySent { get; set; }
        public int UnknownParticipants_TravelAvoided { get; set; }
        public int UnknownParticipants_TravelMaybeAvoided { get; set; }
        public int UnknownParticipants_TravelNotAvoided { get; set; }
        public bool Billable { get; set; }
    
        public virtual KemtahTech KemtahTech { get; set; }
        public virtual Person Requester { get; set; }
        public virtual ICollection<MeetingParticipant> MeetingParticipants { get; set; }
        public virtual ICollection<ExternalLocation> ExternalLocations { get; set; }
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual Series MeetingSeries { get; set; }
    }
}
