//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VtcIts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingParticipant
    {
        public int MeetingId { get; set; }
        public int PersonId { get; set; }
        public bool Attended { get; set; }
        public VtcIts.Ternary TravelAvoided { get; set; }
        public VtcIts.ParticipantType Type { get; set; }
    
        public virtual Meeting Meeting { get; set; }
        public virtual Person Person { get; set; }
    }
}
