//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VtcIts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.RequestedMeetings = new HashSet<Meeting>();
            this.MeetingParticipants = new HashSet<MeetingParticipant>();
        }
    
        public int Id { get; set; }
        public string BadgeNumber { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public int LocationId { get; set; }
        public Nullable<int> BuildingId { get; set; }
    
        public virtual ICollection<Meeting> RequestedMeetings { get; set; }
        public virtual ICollection<MeetingParticipant> MeetingParticipants { get; set; }
        public virtual Building Building { get; set; }
        public virtual Location Location { get; set; }
    }
}
