//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VtcIts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_State
    {
        public Ref_State()
        {
            this.ExternalLocations = new HashSet<ExternalLocation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
    
        public virtual ICollection<ExternalLocation> ExternalLocations { get; set; }
    }
}
