//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VtcIts.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public bool RegistrationAllowed { get; set; }
        public bool EmailEnabled { get; set; }
        public string SurveyLink { get; set; }
        public string SystemMailName { get; set; }
        public string SystemMailAddress { get; set; }
        public int Id { get; set; }
    }
}
